Name: gun2
Species: 8
Parts:
- Name: SK_SCFI_ROBO_06_17HIPS_RO01
  PartType: Hips
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_14ALWR_RO01
  PartType: ArmLowerRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_04_16HNDR_RO01
  PartType: HandRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_05_29ASHL_RO01
  PartType: AttachmentShoulderLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_04_21FOTR_RO01
  PartType: FootRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_13ALWL_RO01
  PartType: ArmLowerLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_06_19LEGR_RO01
  PartType: LegRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_04_20FOTL_RO01
  PartType: FootLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_05_11AUPL_RO01
  PartType: ArmUpperLeft
  PartVersion: 1
- Name: SK_ROBO_BASE_01_01HEAD_RO01
  PartType: Head
  PartVersion: 1
- Name: SK_SCFI_ROBO_05_12AUPR_RO01
  PartType: ArmUpperRight
  PartVersion: 1
- Name: SK_SCFI_ROBO_02_10TORS_RO01
  PartType: Torso
  PartVersion: 1
- Name: SK_SCFI_ROBO_04_15HNDL_RO01
  PartType: HandLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_06_18LEGL_RO01
  PartType: LegLeft
  PartVersion: 1
- Name: SK_SCFI_ROBO_01_24ABAC_RO01
  PartType: AttachmentBack
  PartVersion: 1
- Name: SK_SCFI_ROBO_05_30ASHR_RO01
  PartType: AttachmentShoulderRight
  PartVersion: 1
ColorSet:
  Species: 8
  Name: Custom
  SourceColorPath: Assets\Scenes\GC\Human-Custom\Melee2\Textures\T_Melee2ColorMap.png
  SourceMetallicPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_MetallicMap.png
  SourceSmoothnessPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_SmoothnessMap.png
  SourceReflectionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_ReflectionMap.png
  SourceEmissionPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_EmissionMap.png
  SourceOpacityPath: Assets/Synty/Tools/SidekickCharacters/Resources/Textures/T_OpacityMap.png
ColorRows:
- ColorProperty: 1
  MainColor: F5C2A7
- ColorProperty: 2
  MainColor: F5C2A7
- ColorProperty: 3
  MainColor: F5C2A7
- ColorProperty: 4
  MainColor: F5C2A7
- ColorProperty: 5
  MainColor: E7B39D
- ColorProperty: 6
  MainColor: F5C2A7
- ColorProperty: 7
  MainColor: F5C2A7
- ColorProperty: 8
  MainColor: F5C2A7
- ColorProperty: 9
  MainColor: F5C2A7
- ColorProperty: 10
  MainColor: D7A28B
- ColorProperty: 11
  MainColor: D7A28B
- ColorProperty: 12
  MainColor: D7A28B
- ColorProperty: 13
  MainColor: D7A28B
- ColorProperty: 14
  MainColor: E7B39D
- ColorProperty: 15
  MainColor: EA9999
- ColorProperty: 16
  MainColor: FFF2CC
- ColorProperty: 17
  MainColor: F0E3BB
- ColorProperty: 18
  MainColor: EA9999
- ColorProperty: 19
  MainColor: EA9999
- ColorProperty: 20
  MainColor: AC4641
- ColorProperty: 21
  MainColor: AC4641
- ColorProperty: 22
  MainColor: 999999
- ColorProperty: 23
  MainColor: 999999
- ColorProperty: 24
  MainColor: 666666
- ColorProperty: 25
  MainColor: 666666
- ColorProperty: 26
  MainColor: 151515
- ColorProperty: 27
  MainColor: 151515
- ColorProperty: 28
  MainColor: FFFFFF
- ColorProperty: 29
  MainColor: FFFFFF
- ColorProperty: 30
  MainColor: 26272D
- ColorProperty: 31
  MainColor: 26272D
- ColorProperty: 32
  MainColor: 26272D
- ColorProperty: 33
  MainColor: 26272D
- ColorProperty: 34
  MainColor: B7B7B7
- ColorProperty: 35
  MainColor: 26272D
- ColorProperty: 36
  MainColor: 26272D
- ColorProperty: 37
  MainColor: B7B7B7
- ColorProperty: 38
  MainColor: FFFFFF
- ColorProperty: 39
  MainColor: FFFFFF
- ColorProperty: 40
  MainColor: 65615C
- ColorProperty: 41
  MainColor: 65615C
- ColorProperty: 42
  MainColor: A78E75
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 43
  MainColor: 818849
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 44
  MainColor: 383B50
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 45
  MainColor: 926E4F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 46
  MainColor: 7D6851
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 47
  MainColor: A78E75
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 48
  MainColor: 785630
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 49
  MainColor: 604C33
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 50
  MainColor: 926E4F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 51
  MainColor: 7D6851
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 52
  MainColor: A78E75
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 53
  MainColor: 785630
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 54
  MainColor: 604C33
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 55
  MainColor: 926E4F
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 56
  MainColor: 7D6851
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 57
  MainColor: A58C73
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 58
  MainColor: 7D6851
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 59
  MainColor: 4B3E30
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 60
  MainColor: 907155
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 61
  MainColor: 6A5C4D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 62
  MainColor: A58C73
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 63
  MainColor: 7D6851
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 64
  MainColor: 4B3E30
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 65
  MainColor: 907155
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 66
  MainColor: 6A5C4D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 67
  MainColor: 2E355B
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 68
  MainColor: 4B607F
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 69
  MainColor: 90433B
  Metallic: 545554
  Smoothness: 545554
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 70
  MainColor: 4B3E30
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 71
  MainColor: 6A5C4D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 72
  MainColor: 2E355B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 73
  MainColor: 4B3E30
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 74
  MainColor: 90433B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 75
  MainColor: 4B3E30
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 76
  MainColor: 6A5C4D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 77
  MainColor: 2E355B
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 78
  MainColor: 4B3E30
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 79
  MainColor: 6A5C4D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 80
  MainColor: 4B3E30
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 81
  MainColor: 6A5C4D
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 82
  MainColor: 4B3E30
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 83
  MainColor: 4B3E30
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 84
  MainColor: 3A2F23
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 85
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 86
  MainColor: 575655
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 87
  MainColor: 4B3E30
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 88
  MainColor: 4B3E30
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 89
  MainColor: 3A2F23
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 90
  MainColor: 998B79
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 91
  MainColor: 575655
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 92
  MainColor: 7A593E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 93
  MainColor: 7A593E
  Metallic: 545454
  Smoothness: 545454
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 94
  MainColor: B5B6B5
  Metallic: 525552
  Smoothness: 525552
  Reflection: 000000
  Emission: 000000
  Opacity: FFFFFF
- ColorProperty: 95
  MainColor: 4C3A2D
- ColorProperty: 96
  MainColor: 282E3C
- ColorProperty: 97
  MainColor: 222221
- ColorProperty: 98
  MainColor: 72695E
- ColorProperty: 99
  MainColor: 2A2D31
- ColorProperty: 100
  MainColor: 4C3A2D
- ColorProperty: 101
  MainColor: 2D364C
- ColorProperty: 102
  MainColor: 2A2928
- ColorProperty: 103
  MainColor: 8D806F
- ColorProperty: 104
  MainColor: 32363D
- ColorProperty: 105
  MainColor: 4C3A2D
- ColorProperty: 106
  MainColor: 2D364C
- ColorProperty: 107
  MainColor: 2A2928
- ColorProperty: 108
  MainColor: 8D806F
- ColorProperty: 109
  MainColor: 32363D
- ColorProperty: 110
  MainColor: 7B5650
- ColorProperty: 111
  MainColor: 998B79
- ColorProperty: 112
  MainColor: 514C46
- ColorProperty: 113
  MainColor: 898580
- ColorProperty: 114
  MainColor: 76726C
- ColorProperty: 115
  MainColor: 76554E
- ColorProperty: 116
  MainColor: 918473
- ColorProperty: 117
  MainColor: 504B45
- ColorProperty: 118
  MainColor: 7D7973
- ColorProperty: 119
  MainColor: 6A6660
- ColorProperty: 120
  MainColor: 7B5650
- ColorProperty: 121
  MainColor: 998B79
- ColorProperty: 122
  MainColor: 514C46
- ColorProperty: 123
  MainColor: 898580
- ColorProperty: 124
  MainColor: 76726C
- ColorProperty: 125
  MainColor: 76554E
- ColorProperty: 126
  MainColor: 918473
- ColorProperty: 127
  MainColor: 504B45
- ColorProperty: 128
  MainColor: 7D7973
- ColorProperty: 129
  MainColor: 6A6660
- ColorProperty: 130
  MainColor: 7B5650
- ColorProperty: 131
  MainColor: 998B79
- ColorProperty: 132
  MainColor: 514C46
- ColorProperty: 133
  MainColor: 898580
- ColorProperty: 134
  MainColor: 76726C
- ColorProperty: 135
  MainColor: 76554E
- ColorProperty: 136
  MainColor: 918473
- ColorProperty: 137
  MainColor: 504B45
- ColorProperty: 138
  MainColor: 7D7973
- ColorProperty: 139
  MainColor: 6A6660
- ColorProperty: 140
  MainColor: 7B5650
- ColorProperty: 141
  MainColor: 998B79
- ColorProperty: 142
  MainColor: 514C46
- ColorProperty: 143
  MainColor: 898580
- ColorProperty: 144
  MainColor: 76726C
- ColorProperty: 145
  MainColor: 76554E
- ColorProperty: 146
  MainColor: 918473
- ColorProperty: 147
  MainColor: 504B45
- ColorProperty: 148
  MainColor: 7D7973
- ColorProperty: 149
  MainColor: 6A6660
- ColorProperty: 150
  MainColor: 7B5650
- ColorProperty: 151
  MainColor: 998B79
- ColorProperty: 152
  MainColor: 514C46
- ColorProperty: 153
  MainColor: 898580
- ColorProperty: 154
  MainColor: 76726C
- ColorProperty: 155
  MainColor: 76554E
- ColorProperty: 156
  MainColor: 918473
- ColorProperty: 157
  MainColor: 504B45
- ColorProperty: 158
  MainColor: 7D7973
- ColorProperty: 159
  MainColor: 6A6660
- ColorProperty: 160
  MainColor: 7C7872
- ColorProperty: 161
  MainColor: 65605A
- ColorProperty: 162
  MainColor: 55524A
- ColorProperty: 163
  MainColor: 3D3934
- ColorProperty: 164
  MainColor: 8C8194
- ColorProperty: 165
  MainColor: 796C8A
- ColorProperty: 166
  MainColor: B2A075
- ColorProperty: 167
  MainColor: B29A5C
- ColorProperty: 168
  MainColor: FF9C07
- ColorProperty: 169
  MainColor: FF9C07
- ColorProperty: 170
  MainColor: 33ADA8
- ColorProperty: 171
  MainColor: 33AD77
- ColorProperty: 172
  MainColor: 9A9FA2
- ColorProperty: 173
  MainColor: 949AA2
- ColorProperty: 174
  MainColor: 8D997D
- ColorProperty: 175
  MainColor: 849471
- ColorProperty: 176
  MainColor: 3C3B3A
- ColorProperty: 177
  MainColor: 373635
- ColorProperty: 178
  MainColor: 8E8984
- ColorProperty: 179
  MainColor: 8E8984
- ColorProperty: 180
  MainColor: A29883
- ColorProperty: 181
  MainColor: 9A8F77
- ColorProperty: 182
  MainColor: 8E806F
- ColorProperty: 183
  MainColor: 897967
- ColorProperty: 184
  MainColor: 7D6652
- ColorProperty: 185
  MainColor: 826D5A
- ColorProperty: 186
  MainColor: 716152
- ColorProperty: 187
  MainColor: 685647
- ColorProperty: 188
  MainColor: 998B79
- ColorProperty: 189
  MainColor: 998B79
- ColorProperty: 190
  MainColor: 998B79
- ColorProperty: 191
  MainColor: 998B79
- ColorProperty: 192
  MainColor: AAA5A0
- ColorProperty: 193
  MainColor: AAA5A0
- ColorProperty: 194
  MainColor: 7D6652
- ColorProperty: 195
  MainColor: 8D7057
- ColorProperty: 196
  MainColor: 6D8080
- ColorProperty: 197
  MainColor: 697D9E
- ColorProperty: 198
  MainColor: FFFFFF
- ColorProperty: 199
  MainColor: FFFFFF
- ColorProperty: 200
  MainColor: FFFFFF
- ColorProperty: 201
  MainColor: FFFFFF
- ColorProperty: 202
  MainColor: FFFFFF
- ColorProperty: 203
  MainColor: FFFFFF
- ColorProperty: 204
  MainColor: FFFFFF
- ColorProperty: 205
  MainColor: FFFFFF
- ColorProperty: 206
  MainColor: FFFFFF
- ColorProperty: 207
  MainColor: FFFFFF
- ColorProperty: 208
  MainColor: FFFFFF
- ColorProperty: 209
  MainColor: FFFFFF
BlendShapes:
  BodyTypeValue: -100
  BodySizeValue: -100
  MuscleValue: -65
