//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/TPSRobot/Assets/RPGInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/TPSRobot/Assets/RPGInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @RPGInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @RPGInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""RPGInput"",
    ""maps"": [
        {
            ""name"": ""RPG"",
            ""id"": ""b9f278de-f87c-471f-9175-9045dcacb329"",
            ""actions"": [
                {
                    ""name"": ""GKey"",
                    ""type"": ""Button"",
                    ""id"": ""e7c17a29-da5b-4b0f-a1c6-fa211e1b818d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HKey"",
                    ""type"": ""Button"",
                    ""id"": ""23c14afd-7fb6-41b2-8a0d-47814848a6b2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JKey"",
                    ""type"": ""Button"",
                    ""id"": ""78f44fd0-19c9-4051-aa83-d646a7dd8947"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CAxis"",
                    ""type"": ""Value"",
                    ""id"": ""e2060470-b69f-4ea1-b34b-07e738de1297"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""VAxis"",
                    ""type"": ""Value"",
                    ""id"": ""1b8ae372-9b76-4d49-bdc0-082eb8110b07"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BAxis"",
                    ""type"": ""Value"",
                    ""id"": ""32c47343-100b-449e-b5c0-c8105721b6bd"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Axis"",
                    ""type"": ""Value"",
                    ""id"": ""567bc1f9-e946-4f4e-9e83-230fad1b64aa"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4b476d0a-8623-4551-987b-8e8f77db3633"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b626d87e-c009-409a-91da-09ede73cab4e"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f34665c-d950-4f1d-835d-a61fde3ce704"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f26892d-4ac4-4d2b-aa7f-3914e3ecccb7"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73d5c985-2c3a-4515-88b7-01ab2bd56ab8"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0e76f60-dc5e-4e5b-abef-da76c0acebff"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""92245276-54e9-455b-9f42-dadb3b0e7289"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0ef26675-2763-471b-9300-d7ae3695e06b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6122e94d-191c-4b4d-b8b5-3f1ab79464f4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5f463cd6-01e8-4c57-850f-69dfcaaed918"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f2c57f8d-07a4-4d33-9ceb-6b09a23dbfe1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RPG
        m_RPG = asset.FindActionMap("RPG", throwIfNotFound: true);
        m_RPG_GKey = m_RPG.FindAction("GKey", throwIfNotFound: true);
        m_RPG_HKey = m_RPG.FindAction("HKey", throwIfNotFound: true);
        m_RPG_JKey = m_RPG.FindAction("JKey", throwIfNotFound: true);
        m_RPG_CAxis = m_RPG.FindAction("CAxis", throwIfNotFound: true);
        m_RPG_VAxis = m_RPG.FindAction("VAxis", throwIfNotFound: true);
        m_RPG_BAxis = m_RPG.FindAction("BAxis", throwIfNotFound: true);
        m_RPG_Axis = m_RPG.FindAction("Axis", throwIfNotFound: true);
    }

    ~@RPGInput()
    {
        UnityEngine.Debug.Assert(!m_RPG.enabled, "This will cause a leak and performance issues, RPGInput.RPG.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RPG
    private readonly InputActionMap m_RPG;
    private List<IRPGActions> m_RPGActionsCallbackInterfaces = new List<IRPGActions>();
    private readonly InputAction m_RPG_GKey;
    private readonly InputAction m_RPG_HKey;
    private readonly InputAction m_RPG_JKey;
    private readonly InputAction m_RPG_CAxis;
    private readonly InputAction m_RPG_VAxis;
    private readonly InputAction m_RPG_BAxis;
    private readonly InputAction m_RPG_Axis;
    /// <summary>
    /// Provides access to input actions defined in input action map "RPG".
    /// </summary>
    public struct RPGActions
    {
        private @RPGInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public RPGActions(@RPGInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "RPG/GKey".
        /// </summary>
        public InputAction @GKey => m_Wrapper.m_RPG_GKey;
        /// <summary>
        /// Provides access to the underlying input action "RPG/HKey".
        /// </summary>
        public InputAction @HKey => m_Wrapper.m_RPG_HKey;
        /// <summary>
        /// Provides access to the underlying input action "RPG/JKey".
        /// </summary>
        public InputAction @JKey => m_Wrapper.m_RPG_JKey;
        /// <summary>
        /// Provides access to the underlying input action "RPG/CAxis".
        /// </summary>
        public InputAction @CAxis => m_Wrapper.m_RPG_CAxis;
        /// <summary>
        /// Provides access to the underlying input action "RPG/VAxis".
        /// </summary>
        public InputAction @VAxis => m_Wrapper.m_RPG_VAxis;
        /// <summary>
        /// Provides access to the underlying input action "RPG/BAxis".
        /// </summary>
        public InputAction @BAxis => m_Wrapper.m_RPG_BAxis;
        /// <summary>
        /// Provides access to the underlying input action "RPG/Axis".
        /// </summary>
        public InputAction @Axis => m_Wrapper.m_RPG_Axis;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_RPG; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="RPGActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(RPGActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="RPGActions" />
        public void AddCallbacks(IRPGActions instance)
        {
            if (instance == null || m_Wrapper.m_RPGActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RPGActionsCallbackInterfaces.Add(instance);
            @GKey.started += instance.OnGKey;
            @GKey.performed += instance.OnGKey;
            @GKey.canceled += instance.OnGKey;
            @HKey.started += instance.OnHKey;
            @HKey.performed += instance.OnHKey;
            @HKey.canceled += instance.OnHKey;
            @JKey.started += instance.OnJKey;
            @JKey.performed += instance.OnJKey;
            @JKey.canceled += instance.OnJKey;
            @CAxis.started += instance.OnCAxis;
            @CAxis.performed += instance.OnCAxis;
            @CAxis.canceled += instance.OnCAxis;
            @VAxis.started += instance.OnVAxis;
            @VAxis.performed += instance.OnVAxis;
            @VAxis.canceled += instance.OnVAxis;
            @BAxis.started += instance.OnBAxis;
            @BAxis.performed += instance.OnBAxis;
            @BAxis.canceled += instance.OnBAxis;
            @Axis.started += instance.OnAxis;
            @Axis.performed += instance.OnAxis;
            @Axis.canceled += instance.OnAxis;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="RPGActions" />
        private void UnregisterCallbacks(IRPGActions instance)
        {
            @GKey.started -= instance.OnGKey;
            @GKey.performed -= instance.OnGKey;
            @GKey.canceled -= instance.OnGKey;
            @HKey.started -= instance.OnHKey;
            @HKey.performed -= instance.OnHKey;
            @HKey.canceled -= instance.OnHKey;
            @JKey.started -= instance.OnJKey;
            @JKey.performed -= instance.OnJKey;
            @JKey.canceled -= instance.OnJKey;
            @CAxis.started -= instance.OnCAxis;
            @CAxis.performed -= instance.OnCAxis;
            @CAxis.canceled -= instance.OnCAxis;
            @VAxis.started -= instance.OnVAxis;
            @VAxis.performed -= instance.OnVAxis;
            @VAxis.canceled -= instance.OnVAxis;
            @BAxis.started -= instance.OnBAxis;
            @BAxis.performed -= instance.OnBAxis;
            @BAxis.canceled -= instance.OnBAxis;
            @Axis.started -= instance.OnAxis;
            @Axis.performed -= instance.OnAxis;
            @Axis.canceled -= instance.OnAxis;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="RPGActions.UnregisterCallbacks(IRPGActions)" />.
        /// </summary>
        /// <seealso cref="RPGActions.UnregisterCallbacks(IRPGActions)" />
        public void RemoveCallbacks(IRPGActions instance)
        {
            if (m_Wrapper.m_RPGActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="RPGActions.AddCallbacks(IRPGActions)" />
        /// <seealso cref="RPGActions.RemoveCallbacks(IRPGActions)" />
        /// <seealso cref="RPGActions.UnregisterCallbacks(IRPGActions)" />
        public void SetCallbacks(IRPGActions instance)
        {
            foreach (var item in m_Wrapper.m_RPGActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RPGActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="RPGActions" /> instance referencing this action map.
    /// </summary>
    public RPGActions @RPG => new RPGActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "RPG" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="RPGActions.AddCallbacks(IRPGActions)" />
    /// <seealso cref="RPGActions.RemoveCallbacks(IRPGActions)" />
    public interface IRPGActions
    {
        /// <summary>
        /// Method invoked when associated input action "GKey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGKey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "HKey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHKey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "JKey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJKey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CAxis" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCAxis(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "VAxis" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnVAxis(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BAxis" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBAxis(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Axis" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAxis(InputAction.CallbackContext context);
    }
}
