<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ProjectSExternalAssetsBaseBuilder</AssemblyName>
    <RootNamespace>ProjectS.ExternalAssetsBaseBuilder</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExternalAssetsDeltaCommon\ExternalAssetsDeltaCommon.csproj" />
  </ItemGroup>
</Project>
